import type { ShiftStatus } from "../constants/enums";
import type { UUID, DateString, TimeString, ISODateTime, AuditFields } from "./common";

export interface ShiftTemplate {
  id: UUID;
  outletId: UUID;
  name: string;
  startTime: TimeString;
  endTime: TimeString;
  breakMinutes: number;
  isOvernightShift: boolean;
  color?: string;
  positionIds: UUID[];
  minStaff: number;
  targetStaff: number;
}

export interface ScheduleShift {
  id: UUID;
  scheduleId: UUID;
  templateId?: UUID;
  outletId: UUID;
  departmentId?: UUID;
  positionId?: UUID;
  date: DateString;
  startTime: TimeString;
  endTime: TimeString;
  breakMinutes: number;
  isOvernightShift: boolean;
  minStaff: number;
  targetStaff: number;
  assignedStaff: ShiftAssignment[];
  status: ShiftStatus;
  notes?: string;
}

export interface ShiftAssignment {
  id: UUID;
  shiftId: UUID;
  staffId: UUID;
  staff?: {
    id: UUID;
    name: string;
    employeeId: string;
    avatarUrl?: string;
    positionId: UUID;
  };
  status: ShiftStatus;
  acknowledgedAt?: ISODateTime;
  notes?: string;
}

export interface Schedule {
  id: UUID;
  outletId: UUID;
  weekStartDate: DateString;
  weekEndDate: DateString;
  status: "draft" | "published" | "closed";
  publishedAt?: ISODateTime;
  publishedBy?: UUID;
  autoGenerated: boolean;
  shifts: ScheduleShift[];
  laborCostEstimate?: number;
  coveragePercent?: number;
  createdAt: ISODateTime;
  updatedAt: ISODateTime;
}

export interface GenerateScheduleRequest {
  outletId: UUID;
  weekStartDate: DateString;
  options?: {
    respectLeave?: boolean;
    balanceHours?: boolean;
    minimizeCost?: boolean;
    preferredStaffIds?: UUID[];
  };
}

export interface ShiftSwapRequest {
  id: UUID;
  requesterId: UUID;
  requesterShiftId: UUID;
  targetStaffId?: UUID;
  targetShiftId?: UUID;
  reason?: string;
  status: "pending" | "approved" | "rejected";
  reviewedBy?: UUID;
  reviewedAt?: ISODateTime;
  createdAt: ISODateTime;
}

export interface ScheduleSummary {
  outletId: UUID;
  weekStartDate: DateString;
  totalShifts: number;
  coveredShifts: number;
  coveragePercent: number;
  totalStaffHours: number;
  estimatedLaborCost: number;
  understaffedShifts: number;
  conflictCount: number;
}
